package com.hitchh1k3rsguide.ld27;

public class GameSettings
{
	public static final int SCREEN_WIDTH = 640;
	public static final int SCREEN_HEIGHT = 480;
	public static final int GAME_WIDTH = 320;
	public static final int GAME_HEIGHT = 240;
	public static final String GAME_TITLE = "Time Surge";
	public static final String[] GAME_LOGS = new String[]{
		"                       Time Surge\n\n Our crew are on a secret mission conducting experiments aimed at developing faster than light travel by folding space time. Funding for this quantum exploration has been provided by IPS the Intergalactic Postal Service  whose ultimate goal is to corner the market on galactic delivery, so that they can offer you their service as the best option for your intergalactic postal needs. \n\n              ) Click to start (",
		"Power concerns have been a constant threat to the integrity of this experiment. The Engineer has been rerouting power from the reactor core most of the last few days. This rig could be rather volatile and dangerous but should be fine as long as the Chronostabilizer is not removed before the Device is shut down. Additionally this scientist has made note that particle energy exhibits strange properties (e.g. slowing down and/or speeding up) around the Device even when it is inactive.",
		"Robot's Log:\n I have discovered that acceptable love between human friends is often expressed through hugs. I have been observing the crew, and hugs appear a common greeting between them, particularly between the Scientist and Engineer who are often observed hugging behind the engine. To advance my interpersonal skills with the crew I will begin conducting my own hugging experiments, i.e. I enjoy hugging, do you enjoy hugging, I will hug you, you will hug me, please hug me, hugging is nice/good.",
		"Chef's Log:\n I have never before worked for such a finicky crew! She is lactose intolerant, he will not eat gluten, and that guy is allergic to almost everything! What is a universally celebrated chef to do? At least the captain is not picky, she will eat anything I set in front of her with a smile and an appreciative nod. But alas, I will persist through the pain and anguish of cooking inferior food product for the fastidious masses as I know that my suffering will someday be greatly esteemed.",
		"Captain's Log:\n I woke up this morning in a cold sweat, I was dreaming about that damn robot again. I hate being on this ship with that thing. Sometimes, I could swear it stares directly at me, when it thinks I am not looking, plotting my demise. I wish I could figure out how to get it off my ship without raising suspicions among the rest of the crew. Maybe if I knew how the damned airlock system works, I could deposit it in space and none would be the wiser.",
		"Test Subject's Log:\n Despite the removal of my eye this morning I am so excited to be a part of this mission, good pay, a warm bed to sleep in, and three full meals a day. I could not be more thrilled, feeling so incredibly lucky! For this afternoon's experiment I was listening to this amazing track. Seriously, I did not even feel like dancing but man, it was so hard to resist. In fact I heard from the scientist it was clinically proven to be the most danceable song in the universe!",
		"Security's Log:\n I am certain there is a spy on the ship, I am not sure who they are, but I have been combing through the crew's personal belongings for the last week, trying to find DNA Evidence to run into my Interoga-Tron. Privacy and dignity are luxuries that this crew just cannot afford in this present crisis. I swear, even if I must imprison every member of this crew, I will find the spy. And when I do, they will never be seen again.",
		"Scientist's Log:\n What convinced these executives that a space time folding device is even possible? I mean really, how did that conversation go. So, you should be able to build us a time folding machine, right? It is my role is to come up with these bright ideas to increase our quarterly gains, and your job to execute them. Ugh! I miss my day job in the fuzzie lab. Speaking of fuzzies, oh-no, I think I might have left them in the wrong machine again!",
		"Lieutenant's Log:\n I have deceived you all, no one could have possibly predicted me! I poison the Captain, and the crew blames the Chef. I change the experimental parameters and the Test Subject loses an eye and is framed for my crime. I remove the Chronostabilizer and blame is directed to the engineer for bad wiring. Now, as I flee the scene in my escape pod, there is no one to stopped me from getting away with it. Ha ha, I am the most masterful deceiver and space scoundrel there ever was!",
		"       ) The End ( \n\nCredits: \n\n HitchH1k3r             Programmer \n Naali                        Director \n Solifuge                 Art Assets \n Tlyn                          Writing \n Willfor                   Music \n Mysticstv              Special Thanks \n\n            Thank You For Playing!",
		""
	};
}
